#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pixel Perfect Design System Generator
为 AI coding 应用生成专业级 DESIGN.md 文件
"""

import os
import json
import argparse
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

class PixelPerfectDesignGenerator:
    """像素级完美设计系统生成器"""
    
    def __init__(self, templates_dir: str = None):
        """
        初始化生成器
        
        Args:
            templates_dir: 模板目录路径
        """
        if templates_dir is None:
            templates_dir = Path(__file__).parent.parent / "templates"
        
        self.templates_dir = Path(templates_dir)
        self.available_templates = self._load_template_list()
    
    def _load_template_list(self) -> Dict[str, str]:
        """加载可用模板列表"""
        templates = {
            # AI & Machine Learning
            'claude': 'Claude - 温暖陶土色调，AI 助手风格',
            'cohere': 'Cohere - 企业 AI 平台，渐变丰富',
            'elevenlabs': 'ElevenLabs - AI 语音平台，暗色电影风格',
            'mistral': 'Mistral AI - 开源 LLM，法式极简紫色',
            'ollama': 'Ollama - 本地 LLM，终端优先极简',
            'voltagent': 'VoltAgent - AI agent 框架，翡翠绿深色',
            'xai': 'xAI - Elon Musk AI 实验室，极简单色',
            
            # Developer Tools
            'cursor': 'Cursor - AI 代码编辑器，深色渐变',
            'linear': 'Linear - 项目管理，紫色极简主义',
            'vercel': 'Vercel - 前端部署平台，黑白精准',
            'supabase': 'Supabase - 开源 Firebase，翡翠绿深色',
            'resend': 'Resend - 邮件 API，极简深色',
            'raycast': 'Raycast - 生产力启动器，深色渐变',
            
            # Infrastructure
            'stripe': 'Stripe - 支付基础设施，紫色渐变优雅',
            'mongodb': 'MongoDB - 文档数据库，绿叶品牌',
            'hashicorp': 'HashiCorp - 基础设施自动化，企业级黑白',
            
            # Design Tools
            'notion': 'Notion - 一站式工作区，温暖极简',
            'figma': 'Figma - 协作设计工具，多彩活泼',
            'framer': 'Framer - 网站构建器，黑蓝大胆',
            
            # Enterprise
            'apple': 'Apple - 消费电子，白色极简高级',
            'airbnb': 'Airbnb - 旅游市场，珊瑚色摄影驱动',
            'spotify': 'Spotify - 音乐流媒体，绿色活力',
            'tesla': 'Tesla - 电动汽车，极简未来主义',
        }
        
        return templates
    
    def list_templates(self) -> None:
        """列出所有可用模板"""
        print("\n🎨 Pixel Perfect Design System - 可用模板\n")
        
        categories = {
            'AI & Machine Learning': [],
            'Developer Tools': [],
            'Infrastructure': [],
            'Design Tools': [],
            'Enterprise': [],
        }
        
        for name, description in self.available_templates.items():
            if name in ['claude', 'cohere', 'elevenlabs', 'mistral', 'ollama', 'voltagent', 'xai']:
                categories['AI & Machine Learning'].append((name, description))
            elif name in ['cursor', 'linear', 'vercel', 'supabase', 'resend', 'raycast']:
                categories['Developer Tools'].append((name, description))
            elif name in ['stripe', 'mongodb', 'hashicorp']:
                categories['Infrastructure'].append((name, description))
            elif name in ['notion', 'figma', 'framer']:
                categories['Design Tools'].append((name, description))
            elif name in ['apple', 'airbnb', 'spotify', 'tesla']:
                categories['Enterprise'].append((name, description))
        
        for category, templates in categories.items():
            if templates:
                print(f"\n### {category}")
                for name, description in templates:
                    print(f"  - {name:15s} {description}")
        
        print("\n💡 使用示例:")
        print("  python3 scripts/generate.py --template linear --output DESIGN.md")
        print()
    
    def generate(self, template: str, output: Optional[str] = None) -> str:
        """
        生成 DESIGN.md 文件
        
        Args:
            template: 模板名称
            output: 输出文件路径（可选）
            
        Returns:
            DESIGN.md 内容
        """
        # 检查模板是否存在
        if template.lower() not in self.available_templates:
            print(f"❌ 错误: 模板 '{template}' 不存在")
            print(f"💡 运行 'python3 scripts/generate.py --list' 查看所有可用模板")
            return ""
        
        # 尝试从文件加载
        template_file = self.templates_dir / f"{template.lower()}.md"
        
        if template_file.exists():
            with open(template_file, 'r', encoding='utf-8') as f:
                content = f.read()
        else:
            # 使用简化模板
            content = self._generate_simplified_template(template.lower())
        
        # 添加生成时间戳
        content += f"\n\n---\n**Generated by Pixel Perfect Design System**  \n**Time**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  \n**Template**: {template}\n"
        
        # 保存到文件
        if output:
            output_path = Path(output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"✅ DESIGN.md 已生成: {output}")
        
        return content
    
    def _generate_simplified_template(self, template: str) -> str:
        """生成简化版模板"""
        
        templates_data = {
            'linear': {
                'philosophy': 'Ultra-minimal, precise, developer-centric',
                'mood': 'Technical sophistication with purple accents',
                'primary_color': '#8B5CF6',
                'background': '#000000',
                'accent': '#A78BFA',
                'font': 'Inter',
                'code_font': 'JetBrains Mono',
            },
            'stripe': {
                'philosophy': 'Premium, trustworthy, elegant',
                'mood': 'Sophisticated with gradient richness',
                'primary_color': '#635BFF',
                'background': '#F6F9FC',
                'accent': '#00D4FF',
                'font': 'Stripe-Font',
                'code_font': 'Roboto Mono',
            },
            'notion': {
                'philosophy': 'Warm minimalism, content-first',
                'mood': 'Friendly, productive, calm',
                'primary_color': '#191919',
                'background': '#FFFFFF',
                'accent': '#787774',
                'font': 'Lyon Text',
                'code_font': 'iawriter-mono',
            },
            'vercel': {
                'philosophy': 'Black and white precision',
                'mood': 'Technical, futuristic, minimal',
                'primary_color': '#000000',
                'background': '#FFFFFF',
                'accent': '#0070F3',
                'font': 'Geist Sans',
                'code_font': 'Geist Mono',
            },
            'supabase': {
                'philosophy': 'Developer-friendly, open-source',
                'mood': 'Technical with emerald accents',
                'primary_color': '#10B981',
                'background': '#0F0F0F',
                'accent': '#34D399',
                'font': 'Inter',
                'code_font': 'JetBrains Mono',
            },
        }
        
        data = templates_data.get(template, templates_data['linear'])
        
        return f"""# DESIGN.md - {template.capitalize()} Style

> {data['philosophy']}

---

## 1. Visual Theme & Atmosphere

**Design Philosophy**: {data['philosophy']}  
**Mood**: {data['mood']}  
**Density**: Balanced with purposeful whitespace  
**Design Language**: Modern, clean, minimal

### Design Principles
1. Clarity over decoration
2. Function reveals form
3. User experience first

---

## 2. Color Palette

### Primary Colors

| Name | Hex | Role |
|------|-----|------|
| `primary` | {data['primary_color']} | Primary actions, highlights |
| `background` | {data['background']} | Page background |
| `accent` | {data['accent']} | Accent, secondary actions |

### Semantic Colors

| Name | Hex | Usage |
|------|-----|-------|
| `success` | #10B981 | Success states |
| `warning` | #F59E0B | Warning states |
| `error` | #EF4444 | Error states |
| `info` | #3B82F6 | Informational |

---

## 3. Typography

### Font Families

```css
--font-heading: '{data['font']}', sans-serif;
--font-body: '{data['font']}', sans-serif;
--font-code: '{data['code_font']}', monospace;
```

### Type Scale

| Element | Size | Weight | Line Height |
|---------|------|--------|-------------|
| h1 | 48px | 700 | 1.1 |
| h2 | 32px | 600 | 1.2 |
| h3 | 24px | 600 | 1.3 |
| body | 16px | 400 | 1.5 |
| code | 14px | 400 | 1.6 |

---

## 4. Components

### Buttons

```css
.btn-primary {{
  background: {data['primary_color']};
  color: white;
  padding: 12px 24px;
  border-radius: 6px;
  font-weight: 500;
  transition: all 0.15s ease;
}}

.btn-primary:hover {{
  filter: brightness(1.1);
  transform: translateY(-1px);
}}
```

### Cards

```css
.card {{
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  padding: 16px;
}}
```

---

## 5. Layout

### Spacing Scale

| Name | Value | Usage |
|------|-------|-------|
| xs | 4px | Tight spacing |
| sm | 8px | Small gaps |
| md | 16px | Default spacing |
| lg | 24px | Section spacing |
| xl | 32px | Large spacing |

### Grid System
- Columns: 12
- Gutter: 16px
- Max width: 1200px

---

## 6. Depth & Elevation

```css
--shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.1);
--shadow-md: 0 4px 6px rgba(0, 0, 0, 0.1);
--shadow-lg: 0 10px 15px rgba(0, 0, 0, 0.1);
```

---

## 7. Do's and Don'ts

### ✅ Do
- Use consistent spacing scale
- Follow typography hierarchy
- Test accessibility
- Implement all interaction states

### ❌ Don't
- Use arbitrary spacing values
- Hardcode color values
- Forget responsive design
- Skip accessibility testing

---

## 8. Responsive Behavior

### Breakpoints

| Name | Width |
|------|-------|
| Mobile | < 640px |
| Tablet | 640px - 1024px |
| Desktop | > 1024px |

---

## 9. Agent Prompt Guide

### Quick Reference

```css
--color-primary: {data['primary_color']};
--color-background: {data['background']};
--font-body: '{data['font']}';
--border-radius: 6px;
```

### Common Prompts

**创建页面**:
```
创建一个 [页面名称] 页面，使用 {template.capitalize()} 设计风格：
- 主色调: {data['primary_color']}
- 背景: {data['background']}
- 字体: {data['font']}
- 设计理念: {data['philosophy']}
```

---
"""
    
    def create_custom_design(self, config: Dict, output: Optional[str] = None) -> str:
        """
        根据自定义配置生成 DESIGN.md
        
        Args:
            config: 设计配置字典
            output: 输出文件路径（可选）
            
        Returns:
            DESIGN.md 内容
        """
        # 实现自定义配置生成
        content = self._generate_from_config(config)
        
        if output:
            output_path = Path(output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"✅ 自定义 DESIGN.md 已生成: {output}")
        
        return content
    
    def _generate_from_config(self, config: Dict) -> str:
        """从配置生成 DESIGN.md"""
        # 简化实现
        return f"""# DESIGN.md - Custom Design

## 1. Visual Theme & Atmosphere

**Design Philosophy**: {config.get('philosophy', 'Custom design system')}

## 2. Color Palette

Primary: {config.get('primary_color', '#3B82F6')}
Background: {config.get('background', '#FFFFFF')}

---
"""


def main():
    """主函数"""
    parser = argparse.ArgumentParser(
        description='Pixel Perfect Design System Generator',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  # 列出所有模板
  python3 scripts/generate.py --list
  
  # 生成 Linear 风格 DESIGN.md
  python3 scripts/generate.py --template linear --output DESIGN.md
  
  # 生成 Stripe 风格 DESIGN.md
  python3 scripts/generate.py --template stripe --output DESIGN.md
        """
    )
    
    parser.add_argument('--list', action='store_true', help='列出所有可用模板')
    parser.add_argument('--template', help='使用指定模板生成 DESIGN.md')
    parser.add_argument('--output', help='输出文件路径')
    parser.add_argument('--config', help='自定义配置文件路径（JSON）')
    
    args = parser.parse_args()
    
    generator = PixelPerfectDesignGenerator()
    
    if args.list:
        generator.list_templates()
        return
    
    if args.template:
        generator.generate(args.template, args.output)
        return
    
    if args.config:
        with open(args.config, 'r', encoding='utf-8') as f:
            config = json.load(f)
        generator.create_custom_design(config, args.output)
        return
    
    # 默认：显示帮助
    parser.print_help()


if __name__ == '__main__':
    main()
